In [29]:
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


In [30]:
# Load libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation


In [31]:
df = pd.read_csv('/content/train.csv')

In [32]:
df.head()

Unnamed: 0  Type           Name  Age  Breed1  Breed2  Gender  Color1  \
0           0     2  Yumi Hamasaki    4     292     265       2       1   
1           1     2    Nene/ Kimie   12     285       0       2       5   
2           2     2         Mattie   12     266       0       2       1   
3           3     1            NaN    1     189     307       2       1   
4           4     2           Coco    6     276     285       2       2   

   Color2  Color3  ...  Quantity  Fee  State  \
0       5       7  ...         1    0  41326   
1       6       7  ...         1    0  41326   
2       7       0  ...         1    0  41401   
3       2       0  ...         1    0  41401   
4       4       7  ...         1  100  41326   

                          RescuerID  VideoAmt  \
0  bcc4e1b9557a8b3aaf545ea8e6e86991         0   
1  f0450bf0efe0fa3ff9321d0b827b1237         0   
2  9b52af6d48a4521fd01d4028eb5879a3         0   
3  88da1210e021a5cf43480b074778f3bc         0   
4  227d7b1bcfaffb5f9882bf57b5ee8fab         0   

                                         Description      PetID  PhotoAmt  \
0  I rescued Yumi Hamasaki at a food stall far aw...  7d7a39d71       3.0   
1    Has adopted by a friend with new pet name Kimie  0e107c82f       3.0   
2  I rescued Mattie with a broken leg. After surg...  1a8fd6707       5.0   
3  She born on 30 September . I really hope the a...  bca8b44ae       3.0   
4  Calico Tame and easy going Diet RC Kitten Supp...  2def67952       1.0   

   AdoptionSpeed                  Images  
0              0  images/7d7a39d71-1.jpg  
1              0  images/0e107c82f-1.jpg  
2              0  images/1a8fd6707-1.jpg  
3              0  images/bca8b44ae-1.jpg  
4              0  images/2def67952-1.jpg  

[5 rows x 26 columns]

In [33]:
col_drop=['VideoAmt','Description','PhotoAmt','Images','RescuerID','Health','PetID','Name','Breed1','Breed2','Age']
df = df.drop(columns=col_drop)


In [34]:
df.head()


Unnamed: 0  Type  Gender  Color1  Color2  Color3  MaturitySize  FurLength  \
0           0     2       2       1       5       7             2          2   
1           1     2       2       5       6       7             2          3   
2           2     2       2       1       7       0             2          1   
3           3     1       2       1       2       0             2          1   
4           4     2       2       2       4       7             2          2   

   Vaccinated  Dewormed  Sterilized  Quantity  Fee  State  AdoptionSpeed  
0           1         3           2         1    0  41326              0  
1           2         2           2         1    0  41326              0  
2           1         1           1         1    0  41401              0  
3           1         1           2         1    0  41401              0  
4           1         1           2         1  100  41326              0

In [35]:
df = df.drop(columns=['State'])

In [36]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     600 non-null    int64
 1   Type           600 non-null    int64
 2   Gender         600 non-null    int64
 3   Color1         600 non-null    int64
 4   Color2         600 non-null    int64
 5   Color3         600 non-null    int64
 6   MaturitySize   600 non-null    int64
 7   FurLength      600 non-null    int64
 8   Vaccinated     600 non-null    int64
 9   Dewormed       600 non-null    int64
 10  Sterilized     600 non-null    int64
 11  Quantity       600 non-null    int64
 12  Fee            600 non-null    int64
 13  AdoptionSpeed  600 non-null    int64
dtypes: int64(14)
memory usage: 65.8 KB


In [37]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [38]:
X.shape

(600, 13)

In [39]:
y.shape

(600,)

In [40]:
import pandas as pd

# Assuming 'df' is your DataFrame and 'columns_to_one_hot_encode' is a list of column names
# Replace these with your actual DataFrame and column names

# Create a DataFrame with the columns you want to one-hot encode
df_encoded = pd.get_dummies(df, columns= ['Gender','Color1','Color2','Color3','MaturitySize','FurLength','Vaccinated','Dewormed','Sterilized'], drop_first=True)

# 'drop_first=True' drops the first category in each one-hot encoded column to avoid multicollinearity

# Display the resulting DataFrame
df_encoded.head()


Unnamed: 0  Type  Quantity  Fee  AdoptionSpeed  Gender_2  Gender_3  \
0           0     2         1    0              0         1         0   
1           1     2         1    0              0         1         0   
2           2     2         1    0              0         1         0   
3           3     1         1    0              0         1         0   
4           4     2         1  100              0         1         0   

   Color1_2  Color1_3  Color1_4  ...  MaturitySize_3  MaturitySize_4  \
0         0         0         0  ...               0               0   
1         0         0         0  ...               0               0   
2         0         0         0  ...               0               0   
3         0         0         0  ...               0               0   
4         1         0         0  ...               0               0   

   FurLength_2  FurLength_3  Vaccinated_2  Vaccinated_3  Dewormed_2  \
0            1            0             0             0           0   
1            0            1             1             0           1   
2            0            0             0             0           0   
3            0            0             0             0           0   
4            1            0             0             0           0   

   Dewormed_3  Sterilized_2  Sterilized_3  
0           1             1             0  
1           0             1             0  
2           0             0             0  
3           0             1             0  
4           0             1             0  

[5 rows x 35 columns]

In [41]:
# Concatenate the one-hot encoded DataFrame with the original DataFrame
#df = pd.concat([df, df_encoded], axis=1)

# Drop the original columns (optional, if you want to remove the original columns)
#df = df_encoded.drop(columns=['Gender','Color1','Color2','Color3','MaturitySize','FurLength','Vaccinated','Dewormed','Sterilized'])

# Display the resulting DataFrame
df_encoded.columns

Index(['Unnamed: 0', 'Type', 'Quantity', 'Fee', 'AdoptionSpeed', 'Gender_2',
       'Gender_3', 'Color1_2', 'Color1_3', 'Color1_4', 'Color1_5', 'Color1_6',
       'Color1_7', 'Color2_2', 'Color2_3', 'Color2_4', 'Color2_5', 'Color2_6',
       'Color2_7', 'Color3_3', 'Color3_4', 'Color3_5', 'Color3_6', 'Color3_7',
       'MaturitySize_2', 'MaturitySize_3', 'MaturitySize_4', 'FurLength_2',
       'FurLength_3', 'Vaccinated_2', 'Vaccinated_3', 'Dewormed_2',
       'Dewormed_3', 'Sterilized_2', 'Sterilized_3'],
      dtype='object')

In [42]:
df.head()

Unnamed: 0  Type  Gender  Color1  Color2  Color3  MaturitySize  FurLength  \
0           0     2       2       1       5       7             2          2   
1           1     2       2       5       6       7             2          3   
2           2     2       2       1       7       0             2          1   
3           3     1       2       1       2       0             2          1   
4           4     2       2       2       4       7             2          2   

   Vaccinated  Dewormed  Sterilized  Quantity  Fee  AdoptionSpeed  
0           1         3           2         1    0              0  
1           2         2           2         1    0              0  
2           1         1           1         1    0              0  
3           1         1           2         1    0              0  
4           1         1           2         1  100              0

In [43]:
X = df_encoded.drop(['AdoptionSpeed'], axis =1)
y = df_encoded['AdoptionSpeed']


In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15)

In [45]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit and transform the specified column in the training set
X_train['Fee'] = scaler.fit_transform(X_train[['Fee']])

# Transform the specified column in the testing set

X_test['Fee'] = scaler.transform(X_test[['Fee']])


In [46]:
X_train.reset_index(drop=True)

Unnamed: 0  Type  Quantity       Fee  Gender_2  Gender_3  Color1_2  \
0           294     2         3 -0.280900         0         1         0   
1            73     1         1 -0.280900         0         0         0   
2           436     1         1 -0.280900         1         0         0   
3           312     1         1 -0.280900         0         0         1   
4            55     2         1 -0.280900         0         0         0   
..          ...   ...       ...       ...       ...       ...       ...   
475          85     2         3  0.256408         0         1         0   
476         199     1         1 -0.280900         1         0         0   
477         156     2         1  0.793715         1         0         0   
478         384     2         2 -0.280900         0         0         0   
479         456     2         4 -0.280900         0         1         1   

     Color1_3  Color1_4  Color1_5  ...  MaturitySize_3  MaturitySize_4  \
0           0         0         0  ...               0               0   
1           0         0         1  ...               1               0   
2           0         0         1  ...               0               0   
3           0         0         0  ...               1               0   
4           0         0         0  ...               0               0   
..        ...       ...       ...  ...             ...             ...   
475         0         0         0  ...               0               0   
476         0         0         0  ...               0               0   
477         1         0         0  ...               1               0   
478         0         0         0  ...               0               0   
479         0         0         0  ...               0               0   

     FurLength_2  FurLength_3  Vaccinated_2  Vaccinated_3  Dewormed_2  \
0              0            0             0             1           0   
1              1            0             0             0           0   
2              0            0             0             0           0   
3              0            0             0             0           0   
4              1            0             1             0           1   
..           ...          ...           ...           ...         ...   
475            1            0             1             0           1   
476            1            0             0             0           0   
477            0            1             0             0           0   
478            0            0             1             0           1   
479            0            0             1             0           1   

     Dewormed_3  Sterilized_2  Sterilized_3  
0             1             0             1  
1             0             1             0  
2             0             1             0  
3             0             0             0  
4             0             1             0  
..          ...           ...           ...  
475           0             1             0  
476           0             0             0  
477           0             1             0  
478           0             1             0  
479           0             1             0  

[480 rows x 34 columns]

In [47]:
X_train.shape
X_test.shape

(120, 34)

In [ ]:
type(X_train)

pandas.core.frame.DataFrame

In [ ]:
y_train.shape

(9595,)

In [48]:
from tensorflow.keras import models
from tensorflow.keras.layers import Dense, Dropout


In [49]:
x = np.array(X_train)
y = np.array(y_train)


In [26]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(x,y)

#Predict the response for test dataset
y_pred = clf.predict(X_test)


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


In [27]:
print("y_test shape:", y_test.shape)
print("y_pred shape:", y_pred.shape)


y_test shape: (120,)
y_pred shape: (120,)


In [28]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 1.0


In [50]:
model=models.Sequential([

    Dense(512, activation='relu'),
    Dropout(0.2),
    Dense(256, activation='relu'),
    Dropout(0.2),
    Dense(128, activation='relu'),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(5, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


model.fit(x,y)

15/15 [==============================] - 2s 11ms/step - loss: 3.8936 - accuracy: 0.4250


In [51]:
model.fit(x, y, epochs=500, batch_size=16)


Epoch 1/500
30/30 [==============================] - 1s 10ms/step - loss: 1.8167 - accuracy: 0.4896
Epoch 2/500
30/30 [==============================] - 0s 9ms/step - loss: 1.0889 - accuracy: 0.5479
Epoch 3/500
30/30 [==============================] - 0s 9ms/step - loss: 0.8702 - accuracy: 0.5771
Epoch 4/500
30/30 [==============================] - 0s 9ms/step - loss: 0.8100 - accuracy: 0.6125
Epoch 5/500
30/30 [==============================] - 0s 9ms/step - loss: 0.7002 - accuracy: 0.6458
Epoch 6/500
30/30 [==============================] - 0s 8ms/step - loss: 0.5631 - accuracy: 0.7083
Epoch 7/500
30/30 [==============================] - 0s 8ms/step - loss: 0.5006 - accuracy: 0.7625
Epoch 8/500
30/30 [==============================] - 0s 9ms/step - loss: 0.4184 - accuracy: 0.8062
Epoch 9/500
30/30 [==============================] - 0s 9ms/step - loss: 0.4087 - accuracy: 0.8000
Epoch 10/500
30/30 [==============================] - 0s 9ms/step - loss: 0.4442 - accuracy: 0.7521
Epoch 11

In [53]:
pred=model.predict(X_test)

4/4 [==============================] - 0s 5ms/step


In [54]:
predicted_classes = (pred > 0.5).astype(int)


correct_predictions = (predicted_classes == y_test.values.reshape(-1, 1))

accuracy = np.mean(correct_predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 45.50%


In [ ]:
# Assuming 'model' is your trained TensorFlow model
# and 'X_test' contains the data for which you want predictions

# Make predictions
predictions = model.predict(X_test)

# 'predictions' will contain probability distributions for each class
# If you want class indices (argmax), you can do:
predicted_classes = np.argmax(predictions, axis=1)

# Print or use the predictions
print(predicted_classes)


60/60 [==============================] - 0s 2ms/step
[4 4 4 ... 4 4 4]


In [55]:
# Assuming 'model' is your trained TensorFlow model
# and 'X_test' contains the data for which you want predictions
# and 'y_test' contains the actual labels

# Make predictions
predictions = model.predict(X_test)

# 'predictions' will contain probability distributions for each class
# If you want class indices (argmax), you can do:
predicted_classes = np.argmax(predictions, axis=1)

# Print the first 10 pairs of actual and predicted labels
for actual, predicted in zip(y_test[:20], predicted_classes[:20]):
    print(f"Actual: {actual}, Predicted: {predicted}")


4/4 [==============================] - 0s 5ms/step
Actual: 0, Predicted: 0
Actual: 1, Predicted: 1
Actual: 1, Predicted: 0
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 1, Predicted: 1
Actual: 1, Predicted: 1
Actual: 1, Predicted: 1
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 1, Predicted: 1
Actual: 1, Predicted: 1
Actual: 0, Predicted: 0
Actual: 0, Predicted: 0
Actual: 1, Predicted: 0
Actual: 0, Predicted: 0
Actual: 1, Predicted: 1


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11994 entries, 0 to 11993
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     11994 non-null  int64
 1   Type           11994 non-null  int64
 2   Age            11994 non-null  int64
 3   Breed1         11994 non-null  int64
 4   Breed2         11994 non-null  int64
 5   Gender         11994 non-null  int64
 6   Color1         11994 non-null  int64
 7   Color2         11994 non-null  int64
 8   Color3         11994 non-null  int64
 9   MaturitySize   11994 non-null  int64
 10  FurLength      11994 non-null  int64
 11  Vaccinated     11994 non-null  int64
 12  Dewormed       11994 non-null  int64
 13  Sterilized     11994 non-null  int64
 14  Quantity       11994 non-null  int64
 15  Fee            11994 non-null  int64
 16  State          11994 non-null  int64
 17  AdoptionSpeed  11994 non-null  int64
dtypes: int64(18)
memory usage: 1.6 MB


In [ ]:
df['Color1'].unique()

array([5, 1, 7, 2, 3, 6, 4])

In [ ]:
df['Color2'].unique()

array([0, 2, 7, 5, 6, 4, 3])

In [ ]:
df['Color3'].unique()

array([0, 7, 3, 4, 6, 5])

In [ ]:
df['MaturitySize'].unique()

array([3, 2, 1, 4])

In [ ]:
df['FurLength'].unique()

array([1, 2, 3])

In [ ]:
df['Breed1'].unique

<bound method Series.unique of 0        307
1        266
2        307
3        266
4         20
        ... 
11989    307
11990    292
11991    265
11992    307
11993    266
Name: Breed1, Length: 11994, dtype: int64>

In [ ]:
df['']